/**
* NOTE: This class is auto generated by the template angular2-typescript-service-interface.cshtml.
* Do not edit the class manually.
* * OpenAPI spec version: 0.
* Do not edit the class manually.
*/

import { Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Configuration } from '../configuration.model';
import { Structure } from '../SchemaApi/Models/Structures/Structure';

export interface IStructure {
   defaultHeaders: Headers;
   configuration: Configuration;
   [others: string]: any;

      /**
      * SchemaApi.Controllers.StructureController.ListInApplication (SchemaApi)
      */

      ListInApplication(application : String) : Observable<Array<String>>;
      /**
      * SchemaApi.Controllers.StructureController.List (SchemaApi)
      */

      List() : Observable<Array<String>>;
      /**
      * SchemaApi.Controllers.StructureController.ReadInApplication (SchemaApi)
      */

      ReadInApplication(application : String, name : String) : Observable<Structure>;
      /**
      * SchemaApi.Controllers.StructureController.Read (SchemaApi)
      */

      Read(name : String) : Observable<Structure>;
      /**
      * SchemaApi.Controllers.StructureController.CreateInApplication (SchemaApi)
      */

      CreateInApplication(application : String, name : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.Create (SchemaApi)
      */

      Create(name : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.UpdateInApplication (SchemaApi)
      */

      UpdateInApplication(application : String, lockid : String, item : Structure) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.Update (SchemaApi)
      */

      Update(lockid : String, item : Structure) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.LockInApplication (SchemaApi)
      */

      LockInApplication(application : String, name : String) : Observable<String>;
      /**
      * SchemaApi.Controllers.StructureController.Lock (SchemaApi)
      */

      Lock(name : String) : Observable<String>;
      /**
      * SchemaApi.Controllers.StructureController.UnLockInApplication (SchemaApi)
      */

      UnLockInApplication(application : String, name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.UnLock (SchemaApi)
      */

      UnLock(name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.DeleteInApplication (SchemaApi)
      */

      DeleteInApplication(application : String, name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StructureController.Delete (SchemaApi)
      */

      Delete(name : String, lockid : String) : Observable<{}>;
}

