/**
* NOTE: This class is auto generated by the template angular2-typescript-service-interface.cshtml.
* Do not edit the class manually.
* * OpenAPI spec version: 0.
* Do not edit the class manually.
*/

import { Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Configuration } from '../configuration.model';
import { StoreServerData } from '../SchemaApi/Models/Stores/StoreServerData';

export interface IStore {
   defaultHeaders: Headers;
   configuration: Configuration;
   [others: string]: any;

      /**
      * SchemaApi.Controllers.StoreController.List (SchemaApi)
      */

      List() : Observable<Array<String>>;
      /**
      * SchemaApi.Controllers.StoreController.Read (SchemaApi)
      */

      Read(application : String, name : String) : Observable<StoreServerData>;
      /**
      * SchemaApi.Controllers.StoreController.Create (SchemaApi)
      */

      Create(application : String, name : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.Update (SchemaApi)
      */

      Update(application : String, lockid : String, item : StoreServerData) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.Lock (SchemaApi)
      */

      Lock(application : String, name : String) : Observable<String>;
      /**
      * SchemaApi.Controllers.StoreController.UnLock (SchemaApi)
      */

      UnLock(application : String, name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.Delete (SchemaApi)
      */

      Delete(application : String, name : String, lockid : String) : Observable<{}>;
}

