/**
* NOTE: This class is auto generated by the template angular2-typescript-service-interface.cshtml.
* Do not edit the class manually.
* * OpenAPI spec version: 0.
* Do not edit the class manually.
*/

import { Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Configuration } from '../configuration.model';
import { StoreServerData } from '../SchemaApi/Models/Stores/StoreServerData';

export interface IStore {
   defaultHeaders: Headers;
   configuration: Configuration;
   [others: string]: any;

      /**
      * SchemaApi.Controllers.StoreController.ListInApplication (SchemaApi)
      */

      ListInApplication(application : String) : Observable<Array<String>>;
      /**
      * SchemaApi.Controllers.StoreController.List (SchemaApi)
      */

      List() : Observable<Array<String>>;
      /**
      * SchemaApi.Controllers.StoreController.ReadInApplication (SchemaApi)
      */

      ReadInApplication(application : String, name : String) : Observable<StoreServerData>;
      /**
      * SchemaApi.Controllers.StoreController.Read (SchemaApi)
      */

      Read(name : String) : Observable<StoreServerData>;
      /**
      * SchemaApi.Controllers.StoreController.CreateInApplication (SchemaApi)
      */

      CreateInApplication(application : String, name : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.Create (SchemaApi)
      */

      Create(name : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.UpdateInApplication (SchemaApi)
      */

      UpdateInApplication(application : String, lockid : String, item : StoreServerData) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.Update (SchemaApi)
      */

      Update(lockid : String, item : StoreServerData) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.LockInApplication (SchemaApi)
      */

      LockInApplication(application : String, name : String) : Observable<String>;
      /**
      * SchemaApi.Controllers.StoreController.Lock (SchemaApi)
      */

      Lock(name : String) : Observable<String>;
      /**
      * SchemaApi.Controllers.StoreController.UnLockInApplication (SchemaApi)
      */

      UnLockInApplication(application : String, name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.UnLock (SchemaApi)
      */

      UnLock(name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.DeleteInApplication (SchemaApi)
      */

      DeleteInApplication(application : String, name : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.StoreController.Delete (SchemaApi)
      */

      Delete(name : String, lockid : String) : Observable<{}>;
}

