/**
* NOTE: This class is auto generated by the template angular2-typescript-service-models.cshtml.
* Do not edit the class manually.
*/

import { StructureProperty } from './StructureProperty';
import { TypeKind } from '../TypeKind';

export interface StructureObject {
   Name: String;
   Properties: Array<StructureProperty>;
   Kind: TypeKind;
}

