/**
* NOTE: This class is auto generated by the template angular2-typescript-service-models.cshtml.
* Do not edit the class manually.
*/

import { StructureObjectReference } from '.\StructureObjectReference';
import { StructurePropertyValidatorReference } from '.\StructurePropertyValidatorReference';

export interface StructureProperty {
   Name: String;
   DisplayName: String;
   Description: String;
   Category: String;
   Type: StructureObjectReference;
   Required: boolean;
   IsArray: boolean;
   DefaultValue: String;
   Validators: Array<StructurePropertyValidatorReference>;
}

