/**
* NOTE: This class is auto generated by the template angular2-typescript-service-models.cshtml.
* Do not edit the class manually.
*/


export interface DataModelBase {
   Name: String;
   Created: Date;
   Updated: Date;
   UpdatedBy: String;
   Version: number;
}

