/**
* NOTE: This class is auto generated by the template angular2-typescript-service-interface.cshtml.
* Do not edit the class manually.
* * OpenAPI spec version: 0.
* Do not edit the class manually.
*/

import { Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Configuration } from '../configuration.model';
import { ApplicationStructure } from '../SchemaApi/Models/Structures/ApplicationStructure';

export interface ISchema {
   defaultHeaders: Headers;
   configuration: Configuration;
   [others: string]: any;

      /**
      * SchemaApi.Controllers.SchemaController.GetList (SchemaApi)
      */

      GetList() : Observable<Array<String>>;
      /**
      * SchemaApi.Controllers.SchemaController.Get (SchemaApi)
      */

      Get(applicationName : String) : Observable<ApplicationStructure>;
      /**
      * SchemaApi.Controllers.SchemaController.Post (SchemaApi)
      */

      Post(application : ApplicationStructure, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.SchemaController.Lock (SchemaApi)
      */

      Lock(applicationName : String) : Observable<String>;
      /**
      * SchemaApi.Controllers.SchemaController.UnLock (SchemaApi)
      */

      UnLock(applicationName : String, lockid : String) : Observable<{}>;
      /**
      * SchemaApi.Controllers.SchemaController.Delete (SchemaApi)
      */

      Delete(applicationName : String, lockid : String) : Observable<{}>;
}

