/**
* NOTE: This class is auto generated by the template angular2-typescript-service.cshtml.
* Do not edit the class manually.
*/

import { Inject, Injectable, Optional } from '@angular/core';
import { Http, Headers, URLSearchParams } from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration.model';
import { KeyValuePair`2<String, String> } from '../System/Collections/Generic/KeyValuePair%602';

@Injectable()export class HeartBeat {
   protected basePath: string = 'http://petstore.swagger.io/v2';
   public defaultHeaders: Headers = new Headers();
   public configuration: Configuration = new Configuration();
   constructor(protected http : Http, @Optional() @Inject(BASE_PATH) basePath : string, @Optional() configuration : Configuration) {
      if (basePath) {
         this.basePath = basePath;
      }
      if (configuration) {
         this.configuration = configuration;
      }
   }

       /**
    *
    * Extends object by coping non-existing properties.
    * @@param objA object to be extended
    * @@param objB source object
    */
    private extendObj<T1, T2>
        (objA: T1, objB: T2) {
        for (let key in objB) {
            if (objB.hasOwnProperty(key)) {
                (objA as any)[key] = (objB as any)[key];
            }
        }
        return <T1 & T2>
            objA;
    }

    /**
    * @@param consumes string[] mime-types
    * @@return true: consumes contains 'multipart/form-data', false: otherwise
    */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }

   public Check(key : String) : Observable<Array<KeyValuePair`2<String, String>>> {
      return this.Check_WithHttpInfo(key)
      .map((response: Response) =>  {
         if (response.status === 204) {
            return undefined;
         }
         else {
            return response.json() || { };
         }
      }
      );
   }
   private Check_WithHttpInfo(key : String, extraHttpRequestParams? : any) : Observable<Response> {

      const path = this.basePath + '/api/HeartBeat/{key}';

      let queryParameters = new URLSearchParams();
      let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
      let body : string = '';

      // to determine the Accept header
      let produces: string[] = [ 'application/xml', 'application/json' ];
      if (key !== undefined) {
         queryParameters.set('key', <any> key);
      }

      headers.set('Content-Type', 'application/json');

      let requestOptions: RequestOptionsArgs = new RequestOptions({
       headers: headers,
       method: RequestMethod.Get,
       body:'',
       search: queryParameters,
       withCredentials: this.configuration.withCredentials
      });

      if (extraHttpRequestParams) {
         requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
      }
      return this.http.request(path, requestOptions);
   }

}
