/**
* NOTE: This class is auto generated by the template angular2-typescript-service-interface.cshtml.
* Do not edit the class manually.
* * OpenAPI spec version: 0.
* Do not edit the class manually.
*/

import { Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Configuration } from '../configuration.model';
import { KeyValuePair`2<String, String> } from '../System/Collections/Generic/KeyValuePair%602';

export interface IHeartBeat {
   defaultHeaders: Headers;
   configuration: Configuration;
   [others: string]: any;

      /**
      * SchemaApi.Controllers.HeartBeatController.Check (SchemaApi)
      */

      Check(key : String) : Observable<Array<KeyValuePair`2<String, String>>>;
}

