mongo:
  image: mongo
  restart: always
  hostname: localhost
  container_name: mongo
  command: --rest --httpinterface --replSet rs --smallfiles --oplogSize 200
  volumes:
    - /app/mongo/datas:/data/db
  ports:
    - 27017:27017
    - 28017:28017
  environment:
    - MONGODB_DATABASE=mydatabase
    - MONGODB_USER="admin"
    - MONGODB_PASS="password"

rabbit:
  image: rabbitmq:3-management
  restart: always
  hostname: localhost
  container_name: rabbit
  volumes:
    - /app/rabbit/datas:/data/db
  ports:
    - 8080:15672
    - 5671:5672
    - 25671:25672
    - 15671:15672

