/**
 * molecular api
 * Backend molecular api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * response of get Hertbeatcontroller
 */
export interface HeartbeatResponseList {
    /**
     * Gets or sets the items.
     */
    items?: Array<models.InlineResponse200Items>;

}
