/**
 * molecular api
 * Backend molecular api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * item that describeof one test result on the server
 */
export interface InlineResponse200Items {
    /**
     * Gets or sets the test name.
     */
    test?: string;

    /**
     * Gets or sets the value of the test result.
     */
    value?: string;

    /**
     * Gets or sets a value indicating the test SchemaApi.Models.HeartbeatResponse is succeded.
     */
    succeded?: boolean;

}
