/**
 * molecular api
 * Backend molecular api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InlineResponse2003 {
    objects?: Array<models.InlineResponse2003Objects>;

    name?: string;

    created?: Date;

    updated?: Date;

    updatedBy?: string;

    version?: number;

}
